### ISSUE TITLE
NoneType' object has no attribute 'lower' when missing year in one item of a bibliography

### ISSUE THREAD

**Issue by scoavoux** [scoavoux/PandocTools#8]
If a linked bibtex file has one item missing a year attribute, and that one attempts to trigger PandocCite in a paragraph that *already has a previous reference* cited, the citation panel does not open and the console prints an error `NoneType' object has no attribute 'lower'`

In that case, one can either fix the missing year attribute in the bibliography, or force the panel to open by triggering PandocCite inside square brackets, and immediately after a ; character.

The problem seems to lie in the `prefilter_completion` function in `PandocCite.py`

It might be related to [issue 7](https://github.com/scoavoux/PandocTools/issues/7)

**Comment by theyate** [comment]
This should be fixed.

To present the list of entries, we store a representation of the bibliography with a series of usefull keywords for each entry (title,year, etc). Sometimes, an entry in the .bib file doesn't have a field with this keyword.

The problem was representing unknown fields by `None` in `get_cite_completions`, then calling `.lower()` on all fields in `prefilter_completions`. Calling `None.lower()` results in the error.

The commit  9266759 avoids calling `.lower()` in `prefilter_completions` on objects that interpret as `False` (empty string, `None`). The commit  87e6054 tackles the problem at its source in  `get_cite_completions` : unknown fields are now represented as the empty string : "".
